import type { ExtensionSettings } from './ExtensionSettings';

export const DEFAULT_SETTINGS: ExtensionSettings = {
  provider: 'gemini',
  apiKey: '',
  sourceLanguage: 'auto',
  targetLanguage: 'English',
  autoTranslate: false,
  subtitleFontSize: 24,
  subtitleFontWeight: 600,
  subtitleFontColor: '#FFFFFF',
  subtitleTextShadow: 'strong',
  subtitleLineHeight: 1.3,
  subtitleBackground: '#000000',
  subtitleBackgroundOpacity: 0.75,
  subtitlePosition: 'bottom',
  subtitleVerticalOffset: 0,
  subtitleMaxWidth: 82,
  subtitleAlignment: 'center',
  subtitleBilingual: false,
  bilingualOrder: 'translation-first',
  bilingualOriginalScale: 0.78,
  bilingualOriginalOpacity: 0.72,
  subtitleSyncOffsetMs: 0,
  subtitleMinDuration: 1.4,
  subtitleMaxDuration: 6,
  subtitleReadingSpeed: 'normal',
  duplicateMergeGap: 1,
  subtitleSoundLabels: 'show',
  subtitleMaxLines: 2,
  subtitleMaxCharactersPerLine: 42,
  subtitleMaxCJKCharactersPerLine: 20,
};
